modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    authors="${mod_authors}"
    logoFile="icon.png"
    description='''
    A mod based on GeckoLib that modifies the player model. Originally developed and open sourced by YSM Dev Group. This version is an unofficially forked and modified version by Baiyuanneko from official LegacyYSM mod version 1.1.5. Original credits: bernie-g (GeckoLib), fadookie (mclib), TT432 & SQwatermark (helped the original author solve many difficult problems).

    Notice that this is not the official version of Yes Steve Model or LegacyYSM. The official version of YSM is still actively updating at: https://modrinth.com/mod/yes-steve-model

    For information about this forked version, see: https://github.com/baiyuanneko/legacyysm_unofficial_fork

    ---

    这是一个基于 GeckoLib 魔改玩家模型的模组，原本由 Yes Steve Model 原版团队开发并开源了旧版本（1.1.5），现在由 Baiyuanneko 进行了非官方的 Fork 与修改。原版致谢：bernie-g (GeckoLib), fadookie (mclib), TT432 & SQwatermark (帮助原作者解决了许多艰难的问题).

    这并非 Yes Steve Model 的官方版本，官方版本仍在 https://modrinth.com/mod/yes-steve-model 活跃更新中。

    如对此改版有更多问题和疑问，敬请参考 https://github.com/baiyuanneko/legacyysm_unofficial_fork
    '''

[[accessTransformers]]
    file="META-INF/accesstransformer.cfg"
